In [1]:
!pip install torch torchvision torchaudio

In [2]:
import torch

In [3]:
import torch.nn as nn

In [38]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [39]:
neuron = nn.Linear(in_features=3,out_features=1)

In [40]:
output = neuron(inputs)

In [41]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [42]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [43]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [44]:
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [45]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)